name: muni_stock
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  toast_message_bar: ^0.0.6
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  dio: ^5.7.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  syncfusion_flutter_datagrid: ^27.1.53
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true